file_paths:
  output_file: output_profile_report.html

logging:
  format: "%(asctime)s [%(levelname)s] %(message)s"
  level: INFO

profile_report:
  title: Profiling Report

expected_columns:
  - age
  - ed
  - employ
  - address
  - income
  - debtinc
  - creddebt
  - othdebt
  - default

factorize_columns:
  - ed

standardize_columns:
  - income
  - debtinc
  - creddebt
  - othdebt
