

model_building:
  split_data:
    test_size: 0.2
    random_state: 42

  train_logistic_regression:
    class_weight: balanced





logging:
  level: INFO  
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"  
