name: model_interpretability
channels:
  - conda-forge
  - defaults
dependencies:
    - python=3.11.6
    - numpy=1.24.4
    - pandas=2.0.3
    - matplotlib=3.7.3
    - scikit-learn=1.3.2
    - pip=23.2.1
    - pip:
        - shap==0.43.0
        - lime==0.2.0.1
        - wandb==0.15.12
