name: modeling_conda_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9.18
  - pandas=2.0.3
  - pip=23.2.1
  - requests=2.31.0
  - openpyxl=3.0.10
  - matplotlib=3.8.0
  - numpy=1.24.4
  - scikit-learn=1.3.2
  - joblib=1.3.2
  - imbalanced-learn=0.11.0 
  - pip:
      - wandb==0.15.12




